Tutorials/nlp components
platiagro/tutorials pull request #18
Opened 2021-10-26 17:37 UTC by lucasns97

Add Reader, Retriever, Chunker and translator tutorial files

2021-11-03 11:52 UTC, lucasns97 commented
> No tutorial chunker, sugiro a alteração "Optando por replicar os dados, para cada chunk criado a partir de um campo de texto de uma linha da tabela, todos os dados **desta** linha serão replicados de acordo com a quantidade de chunks produzidos", creio que seria a forma correta.

Muito obrigado @gvechini, fiz as alterações sugeridas

2021-11-09 12:36 UTC, fberanizo requested changes
@lucasns97 fiz alguma sugestões.

2021-11-09 12:36 UTC, fberanizo commented on codelabs/platiagro-tasks/chunker.md
> +Espera-se como retorno numpy arrays contendo a mesma estrutura dos dados de entrada com uma coluna extra correspondente aos chunks produzidos.
Que tal deixar uma sugestão de exemplo de implantação (em formato JSON, como seria pra uma aplicação externa usando o modelo):

``` bash
$ curl --header "Content-Type: application/json" https://URL-DO-MODELO-IMPLANTADO -d "{"data":{"ndarray":[[1, "A bola é um objeto utilizado para lazer e em diversos desportos."]], "names": ["index", "text"]}}"

{"data":{"ndarray":[[1, "A bola é um objeto utilizado para lazer e em diversos desportos.", "A bola é um objeto utilizado para "], [1, "A bola é um objeto utilizado para lazer e em diversos desportos.", "lazer e em diversos desportos."]], "names": ["index", "text", "chunks"]}
```

2021-11-09 12:36 UTC, fberanizo commented on codelabs/platiagro-tasks/reader.md
> +2. ROUGUE-L: A métrica ROUGUE (cujo nome provém de Recall-Oriented Understudy for Gisting Evaluation) identifica a co-ocorrência das substrings mais longas definidas por n-gramas entre as sentenças a
Coloca um link para a wikipedia aqui também :)

2021-11-09 12:36 UTC, fberanizo commented on codelabs/platiagro-tasks/reader.md
> +3. Uma tabela com a pontuação obtida para cada texto pelas métricas BLEU e ROUGUE-L caso seja informado a coluna de avaliação.
Aqui também ROUGUE -> ROUGE

2021-11-09 12:36 UTC, fberanizo commented on codelabs/platiagro-tasks/reader.md
> +Espera-se como retorno numpy arrays contendo a mesma estrutura dos dados de entrada com duas colunas extras correspondentes às respostas produzidas e suas respectivas pontuações.
Aqui também, um exemplo em JSON:

``` bash
$ curl --header "Content-Type: application/json" https://URL-DO-MODELO-IMPLANTADO -d "{"data":{"ndarray":[["A bola é geralmente esférica, mas pode ter outros formatos.", "Qual o formato da bola?"]], "names": ["text", "question"]}}"

{"data":{"ndarray":[["A bola é geralmente esférica, mas pode ter outros formatos.", "Qual o formato da bola?", "esférica", 0.8]], "names": ["text", "question", "answer", "answer_score"]}
```

2021-11-09 12:36 UTC, fberanizo commented on codelabs/platiagro-tasks/reader.md
> +* As métricas computadas são o [BLEU](https://en.wikipedia.org/wiki/BLEU) e o [ROUGUE](https://en.wikipedia.org/wiki/ROUGE_(metric)).
Acredito que a métrica é ROUGE (e não ROUGUE).

O link para o ROUGE ficou quebrado por causa do parênteses. Você pode usar este link no lugar: https://en.wikipedia.org/wiki/ROUGE_%28metric%29

2021-11-09 12:36 UTC, fberanizo commented on codelabs/platiagro-tasks/retriever.md
> +* Observação: Este componente utiliza recursos da internet, portanto é importante estar conectado à rede para que este componente funcione corretamente.
Acho que esta observação pode ser um warning:
```
Negative
: Este componente utiliza recursos da internet, portanto é importante estar conectado à rede para que este componente funcione corretamente.
```

Visualmente fica assim:
![image](https://user-images.githubusercontent.com/1791381/140924124-4fdd7b45-c0d6-489c-9ef3-aa7481a18914.png)

2021-11-09 12:36 UTC, fberanizo commented on codelabs/platiagro-tasks/retriever.md
> +Espera-se como retorno numpy arrays contendo a mesma estrutura dos dados de entrada com duas colunas extras correspondentes às respostas produzidas e suas respectivas pontuações.
Aqui também, é legal colocar em formato JSON.

2021-11-09 12:36 UTC, fberanizo commented on codelabs/platiagro-tasks/retriever.md
> +1. MRR: A métrica MRR (cujo nome provém de Mean Reciprocal Rank) mede a precisão da ordenação dos contextos mais prováveis de conterem a resposta de uma determinada pergunta. Comumente a notação é da
É legal colocar Link para a wikipedia aqui também :)

2021-11-09 12:36 UTC, fberanizo commented on codelabs/platiagro-tasks/translator.md
> +* As métricas computadas são o [BLEU](https://en.wikipedia.org/wiki/BLEU) e o [ROUGUE](https://en.wikipedia.org/wiki/ROUGE_(metric)).
ROUGUE -> ROUGE

2021-11-09 12:36 UTC, fberanizo commented on codelabs/platiagro-tasks/translator.md
> +Espera-se como retorno numpy arrays contendo a mesma estrutura dos dados de entrada com uma coluna extra correspondente aos textos traduzidos.
Aqui também, um exemplo em JSON:

``` bash
$ curl --header "Content-Type: application/json" https://URL-DO-MODELO-IMPLANTADO -d "{"data":{"ndarray":[["A bola é um objeto utilizado para lazer e em diversos desportos."]], "names": ["text"]}}"

{"data":{"ndarray":[["A bola é um objeto utilizado para lazer e em diversos desportos.", "Un ballon est un objet utilisé pour les loisirs et dans divers sports."]], "names": ["text", "text_translated"]}
```

2021-11-09 12:36 UTC, fberanizo commented on codelabs/platiagro-tasks/translator.md
> +2. ROUGUE-L: A métrica ROUGUE (cujo nome provém de Recall-Oriented Understudy for Gisting Evaluation) identifica a co-ocorrência das substrings mais longas definidas por n-gramas entre as sentenças a
ROUGUE->ROUGE 
Links para wiki.

2021-11-09 12:36 UTC, fberanizo commented on codelabs/platiagro-tasks/reader.md
> +* Observação: Este componente utiliza recursos da internet, portanto é importante estar conectado à rede para que este componente funcione corretamente.
Acho que esta observação pode ser um warning:
```
Negative
: Este componente utiliza recursos da internet, portanto é importante estar conectado à rede para que este componente funcione corretamente.
```

Visualmente fica assim:
![image](https://user-images.githubusercontent.com/1791381/140924124-4fdd7b45-c0d6-489c-9ef3-aa7481a18914.png)

2021-11-09 13:37 UTC, lucasns97 commented on codelabs/platiagro-tasks/chunker.md
> +
Puts, entendi! Removido

2021-11-09 13:41 UTC, lucasns97 commented on codelabs/platiagro-tasks/chunker.md
> +* Neste exemplo a aplicação do Chunker é feita separando as expressões considerando as palavras, mas também pode ser realizada considerando períodos.
Os períodos são definidos pelo sent_tokenizer do NLTK que usualmente são divididos por ponto final. Adicionei isso à descrição e a referência da lib.

2021-11-09 13:41 UTC, lucasns97 commented on codelabs/platiagro-tasks/chunker.md
> +* Neste exemplo a aplicação do Chunker é feita separando as expressões considerando as palavras, mas também pode ser realizada considerando períodos.
https://www.nltk.org/api/nltk.tokenize.html

2021-11-09 13:48 UTC, lucasns97 commented on codelabs/platiagro-tasks/chunker.md
> +Espera-se como retorno numpy arrays contendo a mesma estrutura dos dados de entrada com uma coluna extra correspondente aos chunks produzidos.
Muito bom, vou adicionar à todos os tutoriais seguindo a mesma estratégia.

2021-11-09 13:59 UTC, lucasns97 commented on codelabs/platiagro-tasks/reader.md
> +2. ROUGUE-L: A métrica ROUGUE (cujo nome provém de Recall-Oriented Understudy for Gisting Evaluation) identifica a co-ocorrência das substrings mais longas definidas por n-gramas entre as sentenças a
Adicionado!

2021-11-09 13:59 UTC, lucasns97 commented on codelabs/platiagro-tasks/reader.md
> +3. Uma tabela com a pontuação obtida para cada texto pelas métricas BLEU e ROUGUE-L caso seja informado a coluna de avaliação.
Corrigido!

2021-11-09 14:00 UTC, lucasns97 commented on codelabs/platiagro-tasks/reader.md
> +Espera-se como retorno numpy arrays contendo a mesma estrutura dos dados de entrada com duas colunas extras correspondentes às respostas produzidas e suas respectivas pontuações.
Adicionado!

2021-11-09 14:00 UTC, lucasns97 commented on codelabs/platiagro-tasks/reader.md
> +* As métricas computadas são o [BLEU](https://en.wikipedia.org/wiki/BLEU) e o [ROUGUE](https://en.wikipedia.org/wiki/ROUGE_(metric)).
Corrigido!

2021-11-09 14:02 UTC, lucasns97 commented on codelabs/platiagro-tasks/retriever.md
> +* Observação: Este componente utiliza recursos da internet, portanto é importante estar conectado à rede para que este componente funcione corretamente.
Adicionado!

2021-11-09 14:02 UTC, lucasns97 commented on codelabs/platiagro-tasks/retriever.md
> +Espera-se como retorno numpy arrays contendo a mesma estrutura dos dados de entrada com duas colunas extras correspondentes às respostas produzidas e suas respectivas pontuações.
Adicionado!

2021-11-09 14:02 UTC, lucasns97 commented on codelabs/platiagro-tasks/retriever.md
> +1. MRR: A métrica MRR (cujo nome provém de Mean Reciprocal Rank) mede a precisão da ordenação dos contextos mais prováveis de conterem a resposta de uma determinada pergunta. Comumente a notação é da
Adicionado!

2021-11-09 14:02 UTC, lucasns97 commented on codelabs/platiagro-tasks/translator.md
> +* As métricas computadas são o [BLEU](https://en.wikipedia.org/wiki/BLEU) e o [ROUGUE](https://en.wikipedia.org/wiki/ROUGE_(metric)).
Corrigido!

2021-11-09 14:02 UTC, lucasns97 commented on codelabs/platiagro-tasks/translator.md
> +Espera-se como retorno numpy arrays contendo a mesma estrutura dos dados de entrada com uma coluna extra correspondente aos textos traduzidos.
Adicionado!

2021-11-09 14:03 UTC, lucasns97 commented on codelabs/platiagro-tasks/translator.md
> +2. ROUGUE-L: A métrica ROUGUE (cujo nome provém de Recall-Oriented Understudy for Gisting Evaluation) identifica a co-ocorrência das substrings mais longas definidas por n-gramas entre as sentenças a
Corrigido!

2021-11-09 14:03 UTC, lucasns97 commented on codelabs/platiagro-tasks/reader.md
> +* Observação: Este componente utiliza recursos da internet, portanto é importante estar conectado à rede para que este componente funcione corretamente.
Adicionado!

2021-11-09 16:47 UTC, fberanizo approved these changes
👍

2021-11-09 16:55 UTC, merged